<?php

return [
    "系统管理" => [
        '/config',
        '/site/index',
        '/site/logout',
        '/config/index',
        '/config/update',
        '/config/type',
        '/config/others',
        '/config/edit',
        '/config/advertising',
        '/slideshow',
        '/slideshow/index',
        '/slideshow/view',
        '/slideshow/create',
        '/slideshow/update',
        '/slideshow/delete',
        "/gridview/export/download",
        '/slideshow/slideshowremove',
        '/image/upload',
        '/image/delete',
        '/datecontrol/*',
        '/images/upload',
        '/images/remove',
    ],
    "rbac管理" => [
        '/admin/*',
        '/admin/menu',
        '/admin/permission',
        '/admin/role',
        '/admin/assignment',
    ],
//    "缩略图配置" => [
//        '/image-config',
//        '/image-config/index',
//        '/image-config/create',
//        '/image-config/update',
//        '/image-config/view',
//        '/image-config/delete',
//    ],
    "后台用户管理" => [
        '/adminuser',
        '/adminuser/index',
        '/adminuser/view',
        '/adminuser/create',
        '/adminuser/update',
        '/adminuser/resetpwd',
        '/adminuser/delete',
    ],
    "微信配置" => [
        '/wxconfig',
        '/wxconfig/index',
        '/wxconfig/reset',
        '/wxconfig/update',
        '/wxconfig/upload',
        '/wxconfig/txt-upload',
        '/wxconfig/file-delete',
        '/wxconfig/infos',
        '/wxconfig/setting',
    ],
];